version: '3.9'
services:
  api:
    container_name: API
    image: node:16.19.0
    working_dir: /app/backend
    volumes:
      - ./:/app/backend/
    env_file: .env
    ports:
      - 3001:3001
    command: npm run dev
    restart: on-failure
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:
      test: ['CMD', 'lsof', '-t', '-i:3001']
      timeout: 10s
      retries: 5

  mysql:
    container_name: mysql
    image: mysql:5.7.31
    volumes:
      - ./sql/sql.sql:/docker-entrypoint-initdb.d/sql.sql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=improving
    ports:
      - 3002:3306
    command: --default-authentication-plugin=mysql_native_password --sql_mode=NO_ENGINE_SUBSTITUTION,NO_AUTO_CREATE_USER --explicit_defaults_for_timestamp
    restart: always
    healthcheck:
      test:
        ['CMD', 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-proot']
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 30s
